package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * structure for the acceptance filter<br>
 * <i>native declaration : vxlapi.h:698</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class _XLacc_filt extends Structure {
    public byte isSet;
    public int code;
    /**
     * relevant = 1
     */
    public int mask;

    public _XLacc_filt() {
        super(1);
    }

    /**
     * @param mask relevant = 1
     */
    public _XLacc_filt(byte isSet, int code, int mask) {
        super(1);
        this.isSet = isSet;
        this.code = code;
        this.mask = mask;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("isSet", "code", "mask");
    }

    public static class ByReference extends _XLacc_filt implements Structure.ByReference {

    }

    ;

    public static class ByValue extends _XLacc_filt implements Structure.ByValue {

    }

    ;
}
