package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_channel_drv_config_list_v1 extends Structure {
    /**
     * C type : const XLchannelDrvConfigV1*
     */
    public s_xl_channel_drv_config_v1.ByReference item;
    public int count;

    public s_channel_drv_config_list_v1() {
        super(8);
    }

    /**
     * @param item C type : const XLchannelDrvConfigV1*
     */
    public s_channel_drv_config_list_v1(s_xl_channel_drv_config_v1.ByReference item, int count) {
        super(8);
        this.item = item;
        this.count = count;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("item", "count");
    }

    public static class ByReference extends s_channel_drv_config_list_v1 implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_channel_drv_config_list_v1 implements Structure.ByValue {

    }

    ;
}
