package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_most150_async_spy_msg extends Structure {
    public int frameCount;
    /**
     * duration of data packet transmission in [ns]
     */
    public int pktDuration;
    public short asyncDataLenAnnounced;
    public short targetAddress;
    public byte pAck;
    public byte pIndex;
    public short sourceAddress;
    public int crc;
    public int crcCalculated;
    public byte cAck;
    /**
     * number of bytes contained in asyncData[]
     */
    public short asyncDataLen;
    public byte reserved;
    /**
     * currently not used
     */
    public int status;
    public int validMask;
    /**
     * C type : unsigned char[1524]
     */
    public byte[] asyncData = new byte[1524];

    public s_xl_most150_async_spy_msg() {
        super(1);
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("frameCount", "pktDuration", "asyncDataLenAnnounced", "targetAddress", "pAck", "pIndex", "sourceAddress", "crc", "crcCalculated", "cAck", "asyncDataLen", "reserved", "status", "validMask", "asyncData");
    }

    public static class ByReference extends s_xl_most150_async_spy_msg implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_most150_async_spy_msg implements Structure.ByValue {

    }

    ;
}
