package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_kline_set_com_tester extends Structure {
    /**
     * !< [us]
     */
    public int P1min;
    /**
     * !< [us]
     */
    public int P4;
    public int reserved;

    public s_xl_kline_set_com_tester() {
        super(8);
    }

    /**
     * @param P1min !< [us]<br>
     * @param P4    !< [us]
     */
    public s_xl_kline_set_com_tester(int P1min, int P4, int reserved) {
        super(8);
        this.P1min = P1min;
        this.P4 = P4;
        this.reserved = reserved;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("P1min", "P4", "reserved");
    }

    public static class ByReference extends s_xl_kline_set_com_tester implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_kline_set_com_tester implements Structure.ByValue {

    }

    ;
}
