package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_most150_ctrl_sync_audio extends Structure {
    public int label;
    public int width;
    public int device;
    public int mode;

    public s_xl_most150_ctrl_sync_audio() {
        super(1);
    }

    public s_xl_most150_ctrl_sync_audio(int label, int width, int device, int mode) {
        super(1);
        this.label = label;
        this.width = width;
        this.device = device;
        this.mode = mode;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("label", "width", "device", "mode");
    }

    public static class ByReference extends s_xl_most150_ctrl_sync_audio implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_most150_ctrl_sync_audio implements Structure.ByValue {

    }

    ;
}
