package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;
import com.sun.jna.ptr.IntByReference;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_most150_stream_open extends Structure {
    /**
     * C type : unsigned int*
     */
    public IntByReference pStreamHandle;
    public int direction;
    public int numBytesPerFrame;
    public int reserved;
    public int latency;

    public s_xl_most150_stream_open() {
        super(1);
    }

    /**
     * @param pStreamHandle C type : unsigned int*
     */
    public s_xl_most150_stream_open(IntByReference pStreamHandle, int direction, int numBytesPerFrame, int reserved, int latency) {
        super(1);
        this.pStreamHandle = pStreamHandle;
        this.direction = direction;
        this.numBytesPerFrame = numBytesPerFrame;
        this.reserved = reserved;
        this.latency = latency;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("pStreamHandle", "direction", "numBytesPerFrame", "reserved", "latency");
    }

    public static class ByReference extends s_xl_most150_stream_open implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_most150_stream_open implements Structure.ByValue {

    }

    ;
}
