package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_fr_status extends Structure {
    /**
     * !< POC status XL_FR_STATUS_ defines like, normal, active...
     */
    public int statusType;
    public int reserved;

    public s_xl_fr_status() {
        super(8);
    }

    /**
     * @param statusType !< POC status XL_FR_STATUS_ defines like, normal, active...
     */
    public s_xl_fr_status(int statusType, int reserved) {
        super(8);
        this.statusType = statusType;
        this.reserved = reserved;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("statusType", "reserved");
    }

    public static class ByReference extends s_xl_fr_status implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_fr_status implements Structure.ByValue {

    }

    ;
}
