package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_eth_dataframe_rx extends Structure {
    /**
     * FPGA internal identifier unique to every received frame
     */
    public int frameIdentifier;
    /**
     * transmit duration of the Ethernet frame, in nanoseconds
     */
    public int frameDuration;
    /**
     * Overall data length of <frameData>
     */
    public short dataLen;
    /**
     * currently reserved field - not used, ignore
     */
    public short reserved;
    /**
     * currently reserved field - not used, ignore<br>
     * C type : unsigned int[3]
     */
    public int[] reserved2 = new int[3];
    /**
     * Frame Check Sum
     */
    public int fcs;
    /**
     * Destination MAC address<br>
     * C type : unsigned char[6]
     */
    public byte[] destMAC = new byte[6];
    /**
     * Source MAC address<br>
     * C type : unsigned char[6]
     */
    public byte[] sourceMAC = new byte[6];
    /**
     * C type : T_XL_ETH_FRAMEDATA
     */
    public s_xl_eth_framedata frameData;

    public s_xl_eth_dataframe_rx() {
        super(1);
    }

    /**
     * @param frameIdentifier FPGA internal identifier unique to every received frame<br>
     * @param frameDuration   transmit duration of the Ethernet frame, in nanoseconds<br>
     * @param dataLen         Overall data length of <frameData><br>
     * @param reserved        currently reserved field - not used, ignore<br>
     * @param reserved2       currently reserved field - not used, ignore<br>
     *                        C type : unsigned int[3]<br>
     * @param fcs             Frame Check Sum<br>
     * @param destMAC         Destination MAC address<br>
     *                        C type : unsigned char[6]<br>
     * @param sourceMAC       Source MAC address<br>
     *                        C type : unsigned char[6]<br>
     * @param frameData       C type : T_XL_ETH_FRAMEDATA
     */
    public s_xl_eth_dataframe_rx(int frameIdentifier, int frameDuration, short dataLen, short reserved, int reserved2[], int fcs, byte destMAC[], byte sourceMAC[], s_xl_eth_framedata frameData) {
        super(1);
        this.frameIdentifier = frameIdentifier;
        this.frameDuration = frameDuration;
        this.dataLen = dataLen;
        this.reserved = reserved;
        if ((reserved2.length != this.reserved2.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.reserved2 = reserved2;
        this.fcs = fcs;
        if ((destMAC.length != this.destMAC.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.destMAC = destMAC;
        if ((sourceMAC.length != this.sourceMAC.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.sourceMAC = sourceMAC;
        this.frameData = frameData;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("frameIdentifier", "frameDuration", "dataLen", "reserved", "reserved2", "fcs", "destMAC", "sourceMAC", "frameData");
    }

    public static class ByReference extends s_xl_eth_dataframe_rx implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_eth_dataframe_rx implements Structure.ByValue {

    }

    ;
}
