package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_remote_device_info extends Structure {
    /**
     * C type : XLremoteLocationConfig
     */
    public s_xl_remote_location_config locationConfig;
    public int flags;
    public int reserved;
    public int nbrOfDevices;
    /**
     * C type : XLremoteDevice[16]
     */
    public s_xl_remote_device[] deviceInfo = new s_xl_remote_device[16];

    public s_xl_remote_device_info() {
        super(8);
    }

    /**
     * @param locationConfig C type : XLremoteLocationConfig<br>
     * @param deviceInfo     C type : XLremoteDevice[16]
     */
    public s_xl_remote_device_info(s_xl_remote_location_config locationConfig, int flags, int reserved, int nbrOfDevices, s_xl_remote_device deviceInfo[]) {
        super(8);
        this.locationConfig = locationConfig;
        this.flags = flags;
        this.reserved = reserved;
        this.nbrOfDevices = nbrOfDevices;
        if ((deviceInfo.length != this.deviceInfo.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.deviceInfo = deviceInfo;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("locationConfig", "flags", "reserved", "nbrOfDevices", "deviceInfo");
    }

    public static class ByReference extends s_xl_remote_device_info implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_remote_device_info implements Structure.ByValue {

    }

    ;
}
