package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_kline_tester_5bd extends Structure {
    public int tag5bd;
    public int timeDiff;
    public int data;

    public s_xl_kline_tester_5bd() {
        super(1);
    }

    public s_xl_kline_tester_5bd(int tag5bd, int timeDiff, int data) {
        super(1);
        this.tag5bd = tag5bd;
        this.timeDiff = timeDiff;
        this.data = data;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("tag5bd", "timeDiff", "data");
    }

    public static class ByReference extends s_xl_kline_tester_5bd implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_kline_tester_5bd implements Structure.ByValue {

    }

    ;
}
