package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_most150_ctrl_tx_ack extends Structure {
    public short targetAddress;
    public short sourceAddress;
    public byte ctrlPrio;
    public byte ctrlSendAttempts;
    /**
     * C type : unsigned char[2]
     */
    public byte[] reserved = new byte[2];
    public int status;
    /**
     * ctrlData[6..50]: Payload<br>
     * C type : unsigned char[51]
     */
    public byte[] ctrlData = new byte[51];

    public s_xl_most150_ctrl_tx_ack() {
        super(1);
    }

    /**
     * @param reserved C type : unsigned char[2]<br>
     * @param ctrlData ctrlData[6..50]: Payload<br>
     *                 C type : unsigned char[51]
     */
    public s_xl_most150_ctrl_tx_ack(short targetAddress, short sourceAddress, byte ctrlPrio, byte ctrlSendAttempts, byte reserved[], int status, byte ctrlData[]) {
        super(1);
        this.targetAddress = targetAddress;
        this.sourceAddress = sourceAddress;
        this.ctrlPrio = ctrlPrio;
        this.ctrlSendAttempts = ctrlSendAttempts;
        if ((reserved.length != this.reserved.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.reserved = reserved;
        this.status = status;
        if ((ctrlData.length != this.ctrlData.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.ctrlData = ctrlData;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("targetAddress", "sourceAddress", "ctrlPrio", "ctrlSendAttempts", "reserved", "status", "ctrlData");
    }

    public static class ByReference extends s_xl_most150_ctrl_tx_ack implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_most150_ctrl_tx_ack implements Structure.ByValue {

    }

    ;
}
