package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_fr_symbol_window extends Structure {
    /**
     * !< XL_FR_SYMBOL_MTS, ...
     */
    public int symbol;
    /**
     * !< XL_FR_SYMBOL_STATUS_SESA, ...
     */
    public int flags;
    /**
     * !< Actual cyclecount.
     */
    public byte cycleCount;
    /**
     * C type : unsigned char[7]
     */
    public byte[] reserved = new byte[7];

    public s_xl_fr_symbol_window() {
        super(8);
    }

    /**
     * @param symbol     !< XL_FR_SYMBOL_MTS, ...<br>
     * @param flags      !< XL_FR_SYMBOL_STATUS_SESA, ...<br>
     * @param cycleCount !< Actual cyclecount.<br>
     * @param reserved   C type : unsigned char[7]
     */
    public s_xl_fr_symbol_window(int symbol, int flags, byte cycleCount, byte reserved[]) {
        super(8);
        this.symbol = symbol;
        this.flags = flags;
        this.cycleCount = cycleCount;
        if ((reserved.length != this.reserved.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.reserved = reserved;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("symbol", "flags", "cycleCount", "reserved");
    }

    public static class ByReference extends s_xl_fr_symbol_window implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_fr_symbol_window implements Structure.ByValue {

    }

    ;
}
