package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_most150_sync_alloc_info extends Structure {
    /**
     * C type : XL_MOST150_CL_INFO[(unsigned int)372]
     */
    public s_xl_most150_cl_info[] allocTable = new s_xl_most150_cl_info[372];

    public s_xl_most150_sync_alloc_info() {
        super(1);
    }

    /**
     * @param allocTable C type : XL_MOST150_CL_INFO[(unsigned int)372]
     */
    public s_xl_most150_sync_alloc_info(s_xl_most150_cl_info allocTable[]) {
        super(1);
        if ((allocTable.length != this.allocTable.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.allocTable = allocTable;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("allocTable");
    }

    public static class ByReference extends s_xl_most150_sync_alloc_info implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_most150_sync_alloc_info implements Structure.ByValue {

    }

    ;
}
