package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * LIN event structures<br>
 * <i>native declaration : vxlapi.h:213</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_lin_msg extends Structure {
    public byte id;
    public byte dlc;
    public short flags;
    /**
     * C type : unsigned char[8]
     */
    public byte[] data = new byte[8];
    public byte crc;

    public s_xl_lin_msg() {
        super(1);
    }

    /**
     * @param data C type : unsigned char[8]
     */
    public s_xl_lin_msg(byte id, byte dlc, short flags, byte data[], byte crc) {
        super(1);
        this.id = id;
        this.dlc = dlc;
        this.flags = flags;
        if ((data.length != this.data.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.data = data;
        this.crc = crc;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("id", "dlc", "flags", "data", "crc");
    }

    public static class ByReference extends s_xl_lin_msg implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_lin_msg implements Structure.ByValue {

    }

    ;
}
