package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_fr_wakeup extends Structure {
    /**
     * !< Actual cyclecount.
     */
    public byte cycleCount;
    /**
     * !< XL_FR_WAKEUP_UNDEFINED, ...
     */
    public byte wakeupStatus;
    /**
     * C type : unsigned char[6]
     */
    public byte[] reserved = new byte[6];

    public s_xl_fr_wakeup() {
        super(8);
    }

    /**
     * @param cycleCount   !< Actual cyclecount.<br>
     * @param wakeupStatus !< XL_FR_WAKEUP_UNDEFINED, ...<br>
     * @param reserved     C type : unsigned char[6]
     */
    public s_xl_fr_wakeup(byte cycleCount, byte wakeupStatus, byte reserved[]) {
        super(8);
        this.cycleCount = cycleCount;
        this.wakeupStatus = wakeupStatus;
        if ((reserved.length != this.reserved.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.reserved = reserved;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("cycleCount", "wakeupStatus", "reserved");
    }

    public static class ByReference extends s_xl_fr_wakeup implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_fr_wakeup implements Structure.ByValue {

    }

    ;
}
