package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_eth_channel_status extends Structure {
    /**
     * (XL_ETH_STATUS_LINK_*)      Ethernet connection status
     */
    public int link;
    /**
     * (XL_ETH_STATUS_SPEED_*)     Link connection speed
     */
    public int speed;
    /**
     * (XL_ETH_STATUS_DUPLEX_*)    Ethernet duplex mode. 1000Base-T always uses full duplex.
     */
    public int duplex;
    /**
     * (XL_ETH_STATUS_MDI_*)       Currently active MDI-mode
     */
    public int mdiType;
    /**
     * (XL_ETH_STATUS_CONNECTOR_*) Connector (plug) to use (BroadR-REACH or RJ-45).
     */
    public int activeConnector;
    /**
     * (XL_ETH_STATUS_PHY_*)       Currently active physical layer
     */
    public int activePhy;
    /**
     * (XL_ETH_STATUS_CLOCK_*)     When in 1000Base-T or BroadR-mode, currently active mode
     */
    public int clockMode;
    /**
     * (XL_ETH_STATUS_BR_PAIR_*)   When in BroadR-mode, number of used cable pairs
     */
    public int brPairs;

    public s_xl_eth_channel_status() {
        super(4);
    }

    /**
     * @param link            (XL_ETH_STATUS_LINK_*)      Ethernet connection status<br>
     * @param speed           (XL_ETH_STATUS_SPEED_*)     Link connection speed<br>
     * @param duplex          (XL_ETH_STATUS_DUPLEX_*)    Ethernet duplex mode. 1000Base-T always uses full duplex.<br>
     * @param mdiType         (XL_ETH_STATUS_MDI_*)       Currently active MDI-mode<br>
     * @param activeConnector (XL_ETH_STATUS_CONNECTOR_*) Connector (plug) to use (BroadR-REACH or RJ-45).<br>
     * @param activePhy       (XL_ETH_STATUS_PHY_*)       Currently active physical layer<br>
     * @param clockMode       (XL_ETH_STATUS_CLOCK_*)     When in 1000Base-T or BroadR-mode, currently active mode<br>
     * @param brPairs         (XL_ETH_STATUS_BR_PAIR_*)   When in BroadR-mode, number of used cable pairs
     */
    public s_xl_eth_channel_status(int link, int speed, int duplex, int mdiType, int activeConnector, int activePhy, int clockMode, int brPairs) {
        super(4);
        this.link = link;
        this.speed = speed;
        this.duplex = duplex;
        this.mdiType = mdiType;
        this.activeConnector = activeConnector;
        this.activePhy = activePhy;
        this.clockMode = clockMode;
        this.brPairs = brPairs;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("link", "speed", "duplex", "mdiType", "activeConnector", "activePhy", "clockMode", "brPairs");
    }

    public static class ByReference extends s_xl_eth_channel_status implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_eth_channel_status implements Structure.ByValue {

    }

    ;
}
