package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_measurement_point_drv_config_v1 extends Structure {
    /**
     * !< name of the measurement point, NULL terminated UTF-8 encoded string<br>
     * C type : const char*
     */
    public Pointer measurementPointName;
    /**
     * !< the index of the network in the network list this mp belongs to
     */
    public int networkIdx;
    /**
     * !< ID of the switch in the network - switches in different networks may have the same switch ID<br>
     * C type : XLswitchId
     */
    public int switchId;
    /**
     * !< the hardware channel the MP is connected to<br>
     * C type : const XLchannelDrvConfigV1*
     */
    public s_xl_channel_drv_config_v1.ByReference channel;

    public s_xl_measurement_point_drv_config_v1() {
        super(8);
    }

    /**
     * @param measurementPointName !< name of the measurement point, NULL terminated UTF-8 encoded string<br>
     *                             C type : const char*<br>
     * @param networkIdx           !< the index of the network in the network list this mp belongs to<br>
     * @param switchId             !< ID of the switch in the network - switches in different networks may have the same switch ID<br>
     *                             C type : XLswitchId<br>
     * @param channel              !< the hardware channel the MP is connected to<br>
     *                             C type : const XLchannelDrvConfigV1*
     */
    public s_xl_measurement_point_drv_config_v1(Pointer measurementPointName, int networkIdx, int switchId, s_xl_channel_drv_config_v1.ByReference channel) {
        super(8);
        this.measurementPointName = measurementPointName;
        this.networkIdx = networkIdx;
        this.switchId = switchId;
        this.channel = channel;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("measurementPointName", "networkIdx", "switchId", "channel");
    }

    public static class ByReference extends s_xl_measurement_point_drv_config_v1 implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_measurement_point_drv_config_v1 implements Structure.ByValue {

    }

    ;
}
