package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_most_event_source extends Structure {
    public int mask;
    public int state;

    public s_xl_most_event_source() {
        super(8);
    }

    public s_xl_most_event_source(int mask, int state) {
        super(8);
        this.mask = mask;
        this.state = state;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("mask", "state");
    }

    public static class ByReference extends s_xl_most_event_source implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_most_event_source implements Structure.ByValue {

    }

    ;
}
