package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_fr_nm_vector extends Structure {
    /**
     * C type : unsigned char[12]
     */
    public byte[] nmVector = new byte[12];
    /**
     * !< Actual cyclecount.
     */
    public byte cycleCount;
    /**
     * C type : unsigned char[3]
     */
    public byte[] reserved = new byte[3];

    public s_xl_fr_nm_vector() {
        super(8);
    }

    /**
     * @param nmVector   C type : unsigned char[12]<br>
     * @param cycleCount !< Actual cyclecount.<br>
     * @param reserved   C type : unsigned char[3]
     */
    public s_xl_fr_nm_vector(byte[] nmVector, byte cycleCount, byte[] reserved) {
        super(8);
        if ((nmVector.length != this.nmVector.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.nmVector = nmVector;
        this.cycleCount = cycleCount;
        if ((reserved.length != this.reserved.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.reserved = reserved;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("nmVector", "cycleCount", "reserved");
    }

    public static class ByReference extends s_xl_fr_nm_vector implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_fr_nm_vector implements Structure.ByValue {

    }

    ;
}
