package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_fr_start_cycle extends Structure {
    public int cycleCount;
    public int vRateCorrection;
    public int vOffsetCorrection;
    public int vClockCorrectionFailed;
    public int vAllowPassivToActive;
    /**
     * C type : unsigned int[3]
     */
    public int[] reserved = new int[3];

    public s_xl_fr_start_cycle() {
        super(8);
    }

    /**
     * @param reserved C type : unsigned int[3]
     */
    public s_xl_fr_start_cycle(int cycleCount, int vRateCorrection, int vOffsetCorrection, int vClockCorrectionFailed, int vAllowPassivToActive, int reserved[]) {
        super(8);
        this.cycleCount = cycleCount;
        this.vRateCorrection = vRateCorrection;
        this.vOffsetCorrection = vOffsetCorrection;
        this.vClockCorrectionFailed = vClockCorrectionFailed;
        this.vAllowPassivToActive = vAllowPassivToActive;
        if ((reserved.length != this.reserved.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.reserved = reserved;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("cycleCount", "vRateCorrection", "vOffsetCorrection", "vClockCorrectionFailed", "vAllowPassivToActive", "reserved");
    }

    public static class ByReference extends s_xl_fr_start_cycle implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_fr_start_cycle implements Structure.ByValue {

    }

    ;
}
