package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_most_sync_alloc extends Structure {
    /**
     * C type : unsigned char[64]
     */
    public byte[] allocTable = new byte[64];

    public s_xl_most_sync_alloc() {
        super(8);
    }

    /**
     * @param allocTable C type : unsigned char[64]
     */
    public s_xl_most_sync_alloc(byte allocTable[]) {
        super(8);
        if ((allocTable.length != this.allocTable.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.allocTable = allocTable;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("allocTable");
    }

    public static class ByReference extends s_xl_most_sync_alloc implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_most_sync_alloc implements Structure.ByValue {

    }

    ;
}
