package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_most_ctrl_busload_configuration extends Structure {
    public int transmissionRate;
    public int counterType;
    public int counterPosition;
    /**
     * C type : XL_MOST_CTRL_MSG_EV
     */
    public s_xl_most_ctrl_msg busloadCtrlMsg;

    public s_xl_most_ctrl_busload_configuration() {
        super(8);
    }

    /**
     * @param busloadCtrlMsg C type : XL_MOST_CTRL_MSG_EV
     */
    public s_xl_most_ctrl_busload_configuration(int transmissionRate, int counterType, int counterPosition, s_xl_most_ctrl_msg busloadCtrlMsg) {
        super(8);
        this.transmissionRate = transmissionRate;
        this.counterType = counterType;
        this.counterPosition = counterPosition;
        this.busloadCtrlMsg = busloadCtrlMsg;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("transmissionRate", "counterType", "counterPosition", "busloadCtrlMsg");
    }

    public static class ByReference extends s_xl_most_ctrl_busload_configuration implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_most_ctrl_busload_configuration implements Structure.ByValue {

    }

    ;
}
