package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_most150_cl_info extends Structure {
    public short label;
    public short channelWidth;

    public s_xl_most150_cl_info() {
        super(1);
    }

    public s_xl_most150_cl_info(short label, short channelWidth) {
        super(1);
        this.label = label;
        this.channelWidth = channelWidth;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("label", "channelWidth");
    }

    public static class ByReference extends s_xl_most150_cl_info implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_most150_cl_info implements Structure.ByValue {

    }

    ;
}
