package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_most_error extends Structure {
    public int errorCode;
    /**
     * C type : unsigned int[3]
     */
    public int[] parameter = new int[3];

    public s_xl_most_error() {
        super(8);
    }

    /**
     * @param parameter C type : unsigned int[3]
     */
    public s_xl_most_error(int errorCode, int parameter[]) {
        super(8);
        this.errorCode = errorCode;
        if ((parameter.length != this.parameter.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.parameter = parameter;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("errorCode", "parameter");
    }

    public static class ByReference extends s_xl_most_error implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_most_error implements Structure.ByValue {

    }

    ;
}
