package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_most_sync_tx_underflow extends Structure {
    public int streamHandle;
    public int reserved;

    public s_xl_most_sync_tx_underflow() {
        super(8);
    }

    public s_xl_most_sync_tx_underflow(int streamHandle, int reserved) {
        super(8);
        this.streamHandle = streamHandle;
        this.reserved = reserved;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("streamHandle", "reserved");
    }

    public static class ByReference extends s_xl_most_sync_tx_underflow implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_most_sync_tx_underflow implements Structure.ByValue {

    }

    ;
}
