package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_most_register_bits extends Structure {
    public int address;
    public int value;
    public int mask;

    public s_xl_most_register_bits() {
        super(8);
    }

    public s_xl_most_register_bits(int address, int value, int mask) {
        super(8);
        this.address = address;
        this.value = value;
        this.mask = mask;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("address", "value", "mask");
    }

    public static class ByReference extends s_xl_most_register_bits implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_most_register_bits implements Structure.ByValue {

    }

    ;
}
