package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_most150_ctrl_spy extends Structure {
    public int frameCount;
    /**
     * duration of message transmission in [ns]
     */
    public int msgDuration;
    public byte priority;
    public short targetAddress;
    public byte pAck;
    public short ctrlDataLenAnnounced;
    public byte reserved0;
    public byte pIndex;
    public short sourceAddress;
    public short reserved1;
    public short crc;
    public short crcCalculated;
    public byte cAck;
    /**
     * number of bytes contained in ctrlData[]
     */
    public short ctrlDataLen;
    public byte reserved2;
    /**
     * currently not used
     */
    public int status;
    public int validMask;
    /**
     * C type : unsigned char[51]
     */
    public byte[] ctrlData = new byte[51];

    public s_xl_most150_ctrl_spy() {
        super(1);
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("frameCount", "msgDuration", "priority", "targetAddress", "pAck", "ctrlDataLenAnnounced", "reserved0", "pIndex", "sourceAddress", "reserved1", "crc", "crcCalculated", "cAck", "ctrlDataLen", "reserved2", "status", "validMask", "ctrlData");
    }

    public static class ByReference extends s_xl_most150_ctrl_spy implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_most150_ctrl_spy implements Structure.ByValue {

    }

    ;
}
