package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_kline_init_5BdTester extends Structure {
    public int addr;
    public int rate5bd;
    /**
     * !< [us]
     */
    public int W1min;
    /**
     * !< [us]
     */
    public int W1max;
    /**
     * !< [us]
     */
    public int W2min;
    /**
     * !< [us]
     */
    public int W2max;
    /**
     * !< [us]
     */
    public int W3min;
    /**
     * !< [us]
     */
    public int W3max;
    /**
     * !< [us]
     */
    public int W4;
    /**
     * !< [us]
     */
    public int W4min;
    /**
     * !< [us]
     */
    public int W4max;
    public int kb2Not;
    public int reserved;

    public s_xl_kline_init_5BdTester() {
        super(8);
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("addr", "rate5bd", "W1min", "W1max", "W2min", "W2max", "W3min", "W3max", "W4", "W4min", "W4max", "kb2Not", "reserved");
    }

    public static class ByReference extends s_xl_kline_init_5BdTester implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_kline_init_5BdTester implements Structure.ByValue {

    }

    ;
}
