package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_a429_ev_bus_statistic extends Structure {
    /**
     * 0.00-100.00%
     */
    public int busLoad;
    /**
     * C type : unsigned int[3]
     */
    public int[] res1 = new int[3];

    public s_xl_a429_ev_bus_statistic() {
        super(8);
    }

    /**
     * @param busLoad 0.00-100.00%<br>
     * @param res1    C type : unsigned int[3]
     */
    public s_xl_a429_ev_bus_statistic(int busLoad, int res1[]) {
        super(8);
        this.busLoad = busLoad;
        if ((res1.length != this.res1.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.res1 = res1;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("busLoad", "res1");
    }

    public static class ByReference extends s_xl_a429_ev_bus_statistic implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_a429_ev_bus_statistic implements Structure.ByValue {

    }

    ;
}
