package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_most_special_register extends Structure {
    /**
     * see defines "XL_MOST_..._CHANGED"
     */
    public int changeMask;
    public int lockStatus;
    public byte register_bNAH;
    public byte register_bNAL;
    public byte register_bGA;
    public byte register_bAPAH;
    public byte register_bAPAL;
    public byte register_bNPR;
    public byte register_bMPR;
    public byte register_bNDR;
    public byte register_bMDR;
    public byte register_bSBC;
    public byte register_bXTIM;
    public byte register_bXRTY;

    public s_xl_most_special_register() {
        super(8);
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("changeMask", "lockStatus", "register_bNAH", "register_bNAL", "register_bGA", "register_bAPAH", "register_bAPAL", "register_bNPR", "register_bMPR", "register_bNDR", "register_bMDR", "register_bSBC", "register_bXTIM", "register_bXRTY");
    }

    public static class ByReference extends s_xl_most_special_register implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_most_special_register implements Structure.ByValue {

    }

    ;
}
