package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_most150_stream_get_info extends Structure {
    public int streamHandle;
    public int numBytesPerFrame;
    public int direction;
    public int reserved;
    public int latency;
    public int streamState;
    /**
     * C type : unsigned int[8]
     */
    public int[] connLabels = new int[8];

    public s_xl_most150_stream_get_info() {
        super(1);
    }

    /**
     * @param connLabels C type : unsigned int[8]
     */
    public s_xl_most150_stream_get_info(int streamHandle, int numBytesPerFrame, int direction, int reserved, int latency, int streamState, int connLabels[]) {
        super(1);
        this.streamHandle = streamHandle;
        this.numBytesPerFrame = numBytesPerFrame;
        this.direction = direction;
        this.reserved = reserved;
        this.latency = latency;
        this.streamState = streamState;
        if ((connLabels.length != this.connLabels.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.connLabels = connLabels;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("streamHandle", "numBytesPerFrame", "direction", "reserved", "latency", "streamState", "connLabels");
    }

    public static class ByReference extends s_xl_most150_stream_get_info implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_most150_stream_get_info implements Structure.ByValue {

    }

    ;
}
