package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_kline_error_5bd_tester extends Structure {
    public int tester5BdErr;

    public s_xl_kline_error_5bd_tester() {
        super(1);
    }

    public s_xl_kline_error_5bd_tester(int tester5BdErr) {
        super(1);
        this.tester5BdErr = tester5BdErr;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("tester5BdErr");
    }

    public static class ByReference extends s_xl_kline_error_5bd_tester implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_kline_error_5bd_tester implements Structure.ByValue {

    }

    ;
}
