package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;
import com.sun.jna.Union;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_kline_data extends Structure {
    public int klineEvtTag;
    public int reserved;
    /**
     * C type : data_union
     */
    public data_union data;

    public s_xl_kline_data() {
        super(1);
    }

    ;

    /**
     * @param data C type : data_union
     */
    public s_xl_kline_data(int klineEvtTag, int reserved, data_union data) {
        super(1);
        this.klineEvtTag = klineEvtTag;
        this.reserved = reserved;
        this.data = data;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("klineEvtTag", "reserved", "data");
    }

    /**
     * <i>native declaration : vxlapi.h:332</i>
     */
    public static class data_union extends Union {
        /**
         * C type : XL_KLINE_RX_DATA
         */
        public s_xl_kline_rx_data klineRx;
        /**
         * C type : XL_KLINE_TX_DATA
         */
        public s_xl_kline_tx_data klineTx;
        /**
         * C type : XL_KLINE_TESTER_5BD
         */
        public s_xl_kline_tester_5bd klineTester5Bd;
        /**
         * C type : XL_KLINE_ECU_5BD
         */
        public s_xl_kline_ecu_5bd klineEcu5Bd;
        /**
         * C type : XL_KLINE_TESTER_FI_WU_PATTERN
         */
        public s_xl_kline_tester_fastinit_wu_pattern klineTesterFiWu;
        /**
         * C type : XL_KLINE_ECU_FI_WU_PATTERN
         */
        public s_xl_kline_ecu_fastinit_wu_pattern klineEcuFiWu;
        /**
         * C type : XL_KLINE_CONFIRMATION
         */
        public s_xl_kline_confirmation klineConfirmation;
        /**
         * C type : XL_KLINE_ERROR
         */
        public s_xl_kline_error klineError;

        public data_union() {
            super();
        }

        /**
         * @param klineRx C type : XL_KLINE_RX_DATA
         */
        public data_union(s_xl_kline_rx_data klineRx) {
            super();
            this.klineRx = klineRx;
            setType(s_xl_kline_rx_data.class);
        }

        /**
         * @param klineEcu5Bd C type : XL_KLINE_ECU_5BD
         */
        public data_union(s_xl_kline_ecu_5bd klineEcu5Bd) {
            super();
            this.klineEcu5Bd = klineEcu5Bd;
            setType(s_xl_kline_ecu_5bd.class);
        }

        /**
         * @param klineTester5Bd C type : XL_KLINE_TESTER_5BD
         */
        public data_union(s_xl_kline_tester_5bd klineTester5Bd) {
            super();
            this.klineTester5Bd = klineTester5Bd;
            setType(s_xl_kline_tester_5bd.class);
        }

        /**
         * @param klineTx C type : XL_KLINE_TX_DATA
         */
        public data_union(s_xl_kline_tx_data klineTx) {
            super();
            this.klineTx = klineTx;
            setType(s_xl_kline_tx_data.class);
        }

        /**
         * @param klineEcuFiWu C type : XL_KLINE_ECU_FI_WU_PATTERN
         */
        public data_union(s_xl_kline_ecu_fastinit_wu_pattern klineEcuFiWu) {
            super();
            this.klineEcuFiWu = klineEcuFiWu;
            setType(s_xl_kline_ecu_fastinit_wu_pattern.class);
        }

        /**
         * @param klineTesterFiWu C type : XL_KLINE_TESTER_FI_WU_PATTERN
         */
        public data_union(s_xl_kline_tester_fastinit_wu_pattern klineTesterFiWu) {
            super();
            this.klineTesterFiWu = klineTesterFiWu;
            setType(s_xl_kline_tester_fastinit_wu_pattern.class);
        }

        /**
         * @param klineError C type : XL_KLINE_ERROR
         */
        public data_union(s_xl_kline_error klineError) {
            super();
            this.klineError = klineError;
            setType(s_xl_kline_error.class);
        }

        /**
         * @param klineConfirmation C type : XL_KLINE_CONFIRMATION
         */
        public data_union(s_xl_kline_confirmation klineConfirmation) {
            super();
            this.klineConfirmation = klineConfirmation;
            setType(s_xl_kline_confirmation.class);
        }

        public static class ByReference extends data_union implements Structure.ByReference {

        }

        ;

        public static class ByValue extends data_union implements Structure.ByValue {

        }

        ;
    }

    public static class ByReference extends s_xl_kline_data implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_kline_data implements Structure.ByValue {

    }

    ;
}
