package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_application_notification extends Structure {
    /**
     * XL_NOTIFY_REASON_xxx
     */
    public int notifyReason;
    /**
     * C type : unsigned int[7]
     */
    public int[] reserved = new int[7];

    public s_xl_application_notification() {
        super(8);
    }

    /**
     * @param notifyReason XL_NOTIFY_REASON_xxx<br>
     * @param reserved     C type : unsigned int[7]
     */
    public s_xl_application_notification(int notifyReason, int reserved[]) {
        super(8);
        this.notifyReason = notifyReason;
        if ((reserved.length != this.reserved.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.reserved = reserved;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("notifyReason", "reserved");
    }

    public static class ByReference extends s_xl_application_notification implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_application_notification implements Structure.ByValue {

    }

    ;
}
