package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_license_info extends Structure {
    /**
     * !< License is available
     */
    public byte bAvailable;
    /**
     * !< Name of the license as NULL-terminated string<br>
     * C type : char[65]
     */
    public byte[] licName = new byte[65];

    public s_xl_license_info() {
        super();
    }

    /**
     * @param bAvailable !< License is available<br>
     * @param licName    !< Name of the license as NULL-terminated string<br>
     *                   C type : char[65]
     */
    public s_xl_license_info(byte bAvailable, byte licName[]) {
        super();
        this.bAvailable = bAvailable;
        if ((licName.length != this.licName.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.licName = licName;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("bAvailable", "licName");
    }

    public static class ByReference extends s_xl_license_info implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_license_info implements Structure.ByValue {

    }

    ;
}
