package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_net_eth_dataframe_rx extends Structure {
    /**
     * Transmit duration of the Ethernet frame, in nanoseconds
     */
    public int frameDuration;
    /**
     * Overall data length of <frameData>
     */
    public short dataLen;
    /**
     * currently reserved field - not used, ignore
     */
    public byte reserved1;
    /**
     * currently reserved field - not used, ignore
     */
    public byte reserved2;
    /**
     * see XL_ETH_NETWORK_RX_ERROR_xxx and XL_ETH_NETWORK_TX_ERROR_xxx
     */
    public int errorFlags;
    /**
     * currently reserved field - not used, ignore
     */
    public int reserved3;
    /**
     * Frame Check Sum
     */
    public int fcs;
    /**
     * Destination MAC address<br>
     * C type : unsigned char[6]
     */
    public byte[] destMAC = new byte[6];
    /**
     * Source MAC address<br>
     * C type : unsigned char[6]
     */
    public byte[] sourceMAC = new byte[6];
    /**
     * C type : T_XL_ETH_FRAMEDATA
     */
    public s_xl_eth_framedata frameData;

    public s_xl_net_eth_dataframe_rx() {
        super(4);
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("frameDuration", "dataLen", "reserved1", "reserved2", "errorFlags", "reserved3", "fcs", "destMAC", "sourceMAC", "frameData");
    }

    public static class ByReference extends s_xl_net_eth_dataframe_rx implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_net_eth_dataframe_rx implements Structure.ByValue {

    }

    ;
}
