package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_kline_init_5BdEcu extends Structure {
    public int configure;
    public int addr;
    public int rate5bd;
    public int syncPattern;
    /**
     * !< [us]
     */
    public int W1;
    /**
     * !< [us]
     */
    public int W2;
    /**
     * !< [us]
     */
    public int W3;
    /**
     * !< [us]
     */
    public int W4;
    /**
     * !< [us]
     */
    public int W4min;
    /**
     * !< [us]
     */
    public int W4max;
    public int kb1;
    public int kb2;
    public int addrNot;
    public int reserved;

    public s_xl_kline_init_5BdEcu() {
        super(8);
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("configure", "addr", "rate5bd", "syncPattern", "W1", "W2", "W3", "W4", "W4min", "W4max", "kb1", "kb2", "addrNot", "reserved");
    }

    public static class ByReference extends s_xl_kline_init_5BdEcu implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_kline_init_5BdEcu implements Structure.ByValue {

    }

    ;
}
