package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_fr_channel_config extends Structure {
    /**
     * XL_FR_CHANNEL_CFG_STATUS_xxx
     */
    public int status;
    /**
     * XL_FR_CHANNEL_CFG_MODE_xxx
     */
    public int cfgMode;
    /**
     * C type : unsigned int[6]
     */
    public int[] reserved = new int[6];
    /**
     * same as used in function xlFrSetConfig<br>
     * C type : XLfrClusterConfig
     */
    public s_xl_fr_cluster_configuration xlFrClusterConfig;

    public s_xl_fr_channel_config() {
        super(4);
    }

    /**
     * @param status            XL_FR_CHANNEL_CFG_STATUS_xxx<br>
     * @param cfgMode           XL_FR_CHANNEL_CFG_MODE_xxx<br>
     * @param reserved          C type : unsigned int[6]<br>
     * @param xlFrClusterConfig same as used in function xlFrSetConfig<br>
     *                          C type : XLfrClusterConfig
     */
    public s_xl_fr_channel_config(int status, int cfgMode, int reserved[], s_xl_fr_cluster_configuration xlFrClusterConfig) {
        super(4);
        this.status = status;
        this.cfgMode = cfgMode;
        if ((reserved.length != this.reserved.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.reserved = reserved;
        this.xlFrClusterConfig = xlFrClusterConfig;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("status", "cfgMode", "reserved", "xlFrClusterConfig");
    }

    public static class ByReference extends s_xl_fr_channel_config implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_fr_channel_config implements Structure.ByValue {

    }

    ;
}
