package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_most150_ctrl_rx extends Structure {
    public short targetAddress;
    public short sourceAddress;
    public byte fblockId;
    public byte instId;
    public short functionId;
    public byte opType;
    public byte telId;
    public short telLen;
    /**
     * C type : unsigned char[45]
     */
    public byte[] ctrlData = new byte[45];

    public s_xl_most150_ctrl_rx() {
        super(1);
    }

    /**
     * @param ctrlData C type : unsigned char[45]
     */
    public s_xl_most150_ctrl_rx(short targetAddress, short sourceAddress, byte fblockId, byte instId, short functionId, byte opType, byte telId, short telLen, byte ctrlData[]) {
        super(1);
        this.targetAddress = targetAddress;
        this.sourceAddress = sourceAddress;
        this.fblockId = fblockId;
        this.instId = instId;
        this.functionId = functionId;
        this.opType = opType;
        this.telId = telId;
        this.telLen = telLen;
        if ((ctrlData.length != this.ctrlData.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.ctrlData = ctrlData;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("targetAddress", "sourceAddress", "fblockId", "instId", "functionId", "opType", "telId", "telLen", "ctrlData");
    }

    public static class ByReference extends s_xl_most150_ctrl_rx implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_most150_ctrl_rx implements Structure.ByValue {

    }

    ;
}
