package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_kline_confirmation extends Structure {
    public int channel;
    public int confTag;
    public int result;

    public s_xl_kline_confirmation() {
        super(1);
    }

    public s_xl_kline_confirmation(int channel, int confTag, int result) {
        super(1);
        this.channel = channel;
        this.confTag = confTag;
        this.result = result;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("channel", "confTag", "result");
    }

    public static class ByReference extends s_xl_kline_confirmation implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_kline_confirmation implements Structure.ByValue {

    }

    ;
}
