package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_kline_tx_data extends Structure {
    public int timeDiff;
    public int data;
    public int error;

    public s_xl_kline_tx_data() {
        super(1);
    }

    public s_xl_kline_tx_data(int timeDiff, int data, int error) {
        super(1);
        this.timeDiff = timeDiff;
        this.data = data;
        this.error = error;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("timeDiff", "data", "error");
    }

    public static class ByReference extends s_xl_kline_tx_data implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_kline_tx_data implements Structure.ByValue {

    }

    ;
}
