package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;
import com.sun.jna.Union;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h:160</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_daio_piggy_data extends Structure {
    public int daioEvtTag;
    public int triggerType;
    /**
     * C type : data_union
     */
    public data_union data;

    public s_xl_daio_piggy_data() {
        super(1);
    }

    ;

    /**
     * @param data C type : data_union
     */
    public s_xl_daio_piggy_data(int daioEvtTag, int triggerType, data_union data) {
        super(1);
        this.daioEvtTag = daioEvtTag;
        this.triggerType = triggerType;
        this.data = data;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("daioEvtTag", "triggerType", "data");
    }

    /**
     * <i>native declaration : vxlapi.h:164</i>
     */
    public static class data_union extends Union {
        /**
         * C type : XL_IO_DIGITAL_DATA
         */
        public s_xl_io_digital_data digital;
        /**
         * C type : XL_IO_ANALOG_DATA
         */
        public s_xl_io_analog_data analog;

        public data_union() {
            super();
        }

        /**
         * @param analog C type : XL_IO_ANALOG_DATA
         */
        public data_union(s_xl_io_analog_data analog) {
            super();
            this.analog = analog;
            setType(s_xl_io_analog_data.class);
        }

        /**
         * @param digital C type : XL_IO_DIGITAL_DATA
         */
        public data_union(s_xl_io_digital_data digital) {
            super();
            this.digital = digital;
            setType(s_xl_io_digital_data.class);
        }

        public static class ByReference extends data_union implements Structure.ByReference {

        }

        ;

        public static class ByValue extends data_union implements Structure.ByValue {

        }

        ;
    }

    public static class ByReference extends s_xl_daio_piggy_data implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_daio_piggy_data implements Structure.ByValue {

    }

    ;
}
