package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_a429_msg_tx extends Structure {
    public short userHandle;
    public short res1;
    public int flags;
    public int cycleTime;
    public int gap;
    public byte label;
    public byte parity;
    public short res2;
    public int data;

    public s_xl_a429_msg_tx() {
        super(8);
    }

    public s_xl_a429_msg_tx(short userHandle, short res1, int flags, int cycleTime, int gap, byte label, byte parity, short res2, int data) {
        super(8);
        this.userHandle = userHandle;
        this.res1 = res1;
        this.flags = flags;
        this.cycleTime = cycleTime;
        this.gap = gap;
        this.label = label;
        this.parity = parity;
        this.res2 = res2;
        this.data = data;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("userHandle", "res1", "flags", "cycleTime", "gap", "label", "parity", "res2", "data");
    }

    public static class ByReference extends s_xl_a429_msg_tx implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_a429_msg_tx implements Structure.ByValue {

    }

    ;
}
