package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_eth_dataframe_txerror extends Structure {
    /**
     * Error information
     */
    public int errorType;
    /**
     * C type : T_XL_ETH_DATAFRAME_TX_EVENT
     */
    public s_xl_eth_dataframe_tx_event txFrame;

    public s_xl_eth_dataframe_txerror() {
        super();
    }

    /**
     * @param errorType Error information<br>
     * @param txFrame   C type : T_XL_ETH_DATAFRAME_TX_EVENT
     */
    public s_xl_eth_dataframe_txerror(int errorType, s_xl_eth_dataframe_tx_event txFrame) {
        super();
        this.errorType = errorType;
        this.txFrame = txFrame;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("errorType", "txFrame");
    }

    public static class ByReference extends s_xl_eth_dataframe_txerror implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_eth_dataframe_txerror implements Structure.ByValue {

    }

    ;
}
