package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h:192</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_transceiver extends Structure {
    /**
     * !< reason for what was event sent
     */
    public byte event_reason;
    /**
     * !< allways valid transceiver presence flag
     */
    public byte is_present;

    public s_xl_transceiver() {
        super(1);
    }

    /**
     * @param event_reason !< reason for what was event sent<br>
     * @param is_present   !< allways valid transceiver presence flag
     */
    public s_xl_transceiver(byte event_reason, byte is_present) {
        super(1);
        this.event_reason = event_reason;
        this.is_present = is_present;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("event_reason", "is_present");
    }

    public static class ByReference extends s_xl_transceiver implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_transceiver implements Structure.ByValue {

    }

    ;
}
