package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Union;

/**
 * BASIC bus message structure<br>
 * <i>native declaration : vxlapi.h:351</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_tag_data extends Union {
    /**
     * C type : s_xl_can_msg
     */
    public s_xl_can_msg msg;
    /**
     * C type : s_xl_chip_state
     */
    public s_xl_chip_state chipState;
    /**
     * C type : s_xl_lin_msg_api
     */
    public s_xl_lin_msg_api linMsgApi;
    /**
     * C type : s_xl_sync_pulse
     */
    public s_xl_sync_pulse syncPulse;
    /**
     * C type : s_xl_daio_data
     */
    public s_xl_daio_data daioData;
    /**
     * C type : s_xl_transceiver
     */
    public s_xl_transceiver transceiver;
    /**
     * C type : s_xl_daio_piggy_data
     */
    public s_xl_daio_piggy_data daioPiggyData;
    /**
     * C type : s_xl_kline_data
     */
    public s_xl_kline_data klineData;

    public s_xl_tag_data() {
        super();
    }

    /**
     * @param daioPiggyData C type : s_xl_daio_piggy_data
     */
    public s_xl_tag_data(s_xl_daio_piggy_data daioPiggyData) {
        super();
        this.daioPiggyData = daioPiggyData;
        setType(s_xl_daio_piggy_data.class);
    }

    /**
     * @param daioData C type : s_xl_daio_data
     */
    public s_xl_tag_data(s_xl_daio_data daioData) {
        super();
        this.daioData = daioData;
        setType(s_xl_daio_data.class);
    }

    /**
     * @param klineData C type : s_xl_kline_data
     */
    public s_xl_tag_data(s_xl_kline_data klineData) {
        super();
        this.klineData = klineData;
        setType(s_xl_kline_data.class);
    }

    /**
     * @param linMsgApi C type : s_xl_lin_msg_api
     */
    public s_xl_tag_data(s_xl_lin_msg_api linMsgApi) {
        super();
        this.linMsgApi = linMsgApi;
        setType(s_xl_lin_msg_api.class);
    }

    /**
     * @param msg C type : s_xl_can_msg
     */
    public s_xl_tag_data(s_xl_can_msg msg) {
        super();
        this.msg = msg;
        setType(s_xl_can_msg.class);
    }

    /**
     * @param syncPulse C type : s_xl_sync_pulse
     */
    public s_xl_tag_data(s_xl_sync_pulse syncPulse) {
        super();
        this.syncPulse = syncPulse;
        setType(s_xl_sync_pulse.class);
    }

    /**
     * @param transceiver C type : s_xl_transceiver
     */
    public s_xl_tag_data(s_xl_transceiver transceiver) {
        super();
        this.transceiver = transceiver;
        setType(s_xl_transceiver.class);
    }

    /**
     * @param chipState C type : s_xl_chip_state
     */
    public s_xl_tag_data(s_xl_chip_state chipState) {
        super();
        this.chipState = chipState;
        setType(s_xl_chip_state.class);
    }

    public static class ByReference extends s_xl_tag_data implements com.sun.jna.Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_tag_data implements com.sun.jna.Structure.ByValue {

    }

    ;
}
