package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_most150_ethernet_spy extends Structure {
    public int frameCount;
    /**
     * duration of ethernet packet transmission in [ns]
     */
    public int pktDuration;
    public short ethernetDataLenAnnounced;
    /**
     * C type : unsigned char[6]
     */
    public byte[] targetAddress = new byte[6];
    public byte pAck;
    /**
     * C type : unsigned char[6]
     */
    public byte[] sourceAddress = new byte[6];
    public byte reserved0;
    public int crc;
    public int crcCalculated;
    public byte cAck;
    /**
     * number of bytes contained in ethernetData[]
     */
    public short ethernetDataLen;
    public byte reserved1;
    /**
     * currently not used
     */
    public int status;
    public int validMask;
    /**
     * C type : unsigned char[1506]
     */
    public byte[] ethernetData = new byte[1506];

    public s_xl_most150_ethernet_spy() {
        super(1);
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("frameCount", "pktDuration", "ethernetDataLenAnnounced", "targetAddress", "pAck", "sourceAddress", "reserved0", "crc", "crcCalculated", "cAck", "ethernetDataLen", "reserved1", "status", "validMask", "ethernetData");
    }

    public static class ByReference extends s_xl_most150_ethernet_spy implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_most150_ethernet_spy implements Structure.ByValue {

    }

    ;
}
