package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_most150_stream_state extends Structure {
    public int streamHandle;
    public int streamState;
    public int streamError;

    public s_xl_most150_stream_state() {
        super(1);
    }

    public s_xl_most150_stream_state(int streamHandle, int streamState, int streamError) {
        super(1);
        this.streamHandle = streamHandle;
        this.streamState = streamState;
        this.streamError = streamError;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("streamHandle", "streamState", "streamError");
    }

    public static class ByReference extends s_xl_most150_stream_state implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_most150_stream_state implements Structure.ByValue {

    }

    ;
}
