package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_a429_ev_rx_err extends Structure {
    public int frameLength;
    public int bitrate;
    public int bitLengthOfLastBit;
    public byte errorPosition;
    public byte errorReason;
    public byte label;
    public byte res1;
    public int data;

    public s_xl_a429_ev_rx_err() {
        super(8);
    }

    public s_xl_a429_ev_rx_err(int frameLength, int bitrate, int bitLengthOfLastBit, byte errorPosition, byte errorReason, byte label, byte res1, int data) {
        super(8);
        this.frameLength = frameLength;
        this.bitrate = bitrate;
        this.bitLengthOfLastBit = bitLengthOfLastBit;
        this.errorPosition = errorPosition;
        this.errorReason = errorReason;
        this.label = label;
        this.res1 = res1;
        this.data = data;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("frameLength", "bitrate", "bitLengthOfLastBit", "errorPosition", "errorReason", "label", "res1", "data");
    }

    public static class ByReference extends s_xl_a429_ev_rx_err implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_a429_ev_rx_err implements Structure.ByValue {

    }

    ;
}
