package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h:2</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_sync_pulse extends Structure {
    /**
     * !< generated by us
     */
    public byte pulseCode;
    /**
     * !< 1 ns resolution<br>
     * C type : XLuint64
     */
    public long time;

    public s_xl_sync_pulse() {
        super(1);
    }

    /**
     * @param pulseCode !< generated by us<br>
     * @param time      !< 1 ns resolution<br>
     *                  C type : XLuint64
     */
    public s_xl_sync_pulse(byte pulseCode, long time) {
        super(1);
        this.pulseCode = pulseCode;
        this.time = time;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("pulseCode", "time");
    }

    public static class ByReference extends s_xl_sync_pulse implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_sync_pulse implements Structure.ByValue {

    }

    ;
}
