package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h:179</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_chip_state extends Structure {
    public byte busStatus;
    public byte txErrorCounter;
    public byte rxErrorCounter;

    public s_xl_chip_state() {
        super(1);
    }

    public s_xl_chip_state(byte busStatus, byte txErrorCounter, byte rxErrorCounter) {
        super(1);
        this.busStatus = busStatus;
        this.txErrorCounter = txErrorCounter;
        this.rxErrorCounter = rxErrorCounter;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("busStatus", "txErrorCounter", "rxErrorCounter");
    }

    public static class ByReference extends s_xl_chip_state implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_chip_state implements Structure.ByValue {

    }

    ;
}
