package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_fr_error extends Structure {
    public byte tag;
    public byte cycleCount;
    /**
     * C type : unsigned char[6]
     */
    public byte[] reserved = new byte[6];
    /**
     * C type : s_xl_fr_error_info
     */
    public s_xl_fr_error_info errorInfo;

    public s_xl_fr_error() {
        super(8);
    }

    /**
     * @param reserved  C type : unsigned char[6]<br>
     * @param errorInfo C type : s_xl_fr_error_info
     */
    public s_xl_fr_error(byte tag, byte cycleCount, byte reserved[], s_xl_fr_error_info errorInfo) {
        super(8);
        this.tag = tag;
        this.cycleCount = cycleCount;
        if ((reserved.length != this.reserved.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.reserved = reserved;
        this.errorInfo = errorInfo;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("tag", "cycleCount", "reserved", "errorInfo");
    }

    public static class ByReference extends s_xl_fr_error implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_fr_error implements Structure.ByValue {

    }

    ;
}
