package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_most_register_bytes extends Structure {
    public int number;
    public int address;
    /**
     * C type : unsigned char[16]
     */
    public byte[] value = new byte[16];

    public s_xl_most_register_bytes() {
        super(8);
    }

    /**
     * @param value C type : unsigned char[16]
     */
    public s_xl_most_register_bytes(int number, int address, byte value[]) {
        super(8);
        this.number = number;
        this.address = address;
        if ((value.length != this.value.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.value = value;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("number", "address", "value");
    }

    public static class ByReference extends s_xl_most_register_bytes implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_most_register_bytes implements Structure.ByValue {

    }

    ;
}
