package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_fr_error_sync_frames extends Structure {
    /**
     * !< valid RX/TX sync frames on frCh A for even cycles
     */
    public short evenSyncFramesA;
    /**
     * !< valid RX/TX sync frames on frCh A for odd cycles
     */
    public short oddSyncFramesA;
    /**
     * !< valid RX/TX sync frames on frCh B for even cycles
     */
    public short evenSyncFramesB;
    /**
     * !< valid RX/TX sync frames on frCh B for odd cycles
     */
    public short oddSyncFramesB;
    public int reserved;

    public s_xl_fr_error_sync_frames() {
        super(8);
    }

    /**
     * @param evenSyncFramesA !< valid RX/TX sync frames on frCh A for even cycles<br>
     * @param oddSyncFramesA  !< valid RX/TX sync frames on frCh A for odd cycles<br>
     * @param evenSyncFramesB !< valid RX/TX sync frames on frCh B for even cycles<br>
     * @param oddSyncFramesB  !< valid RX/TX sync frames on frCh B for odd cycles
     */
    public s_xl_fr_error_sync_frames(short evenSyncFramesA, short oddSyncFramesA, short evenSyncFramesB, short oddSyncFramesB, int reserved) {
        super(8);
        this.evenSyncFramesA = evenSyncFramesA;
        this.oddSyncFramesA = oddSyncFramesA;
        this.evenSyncFramesB = evenSyncFramesB;
        this.oddSyncFramesB = oddSyncFramesB;
        this.reserved = reserved;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("evenSyncFramesA", "oddSyncFramesA", "evenSyncFramesB", "oddSyncFramesB", "reserved");
    }

    public static class ByReference extends s_xl_fr_error_sync_frames implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_fr_error_sync_frames implements Structure.ByValue {

    }

    ;
}
