package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_fr_spy_frame extends Structure {
    public int frameLength;
    /**
     * !< XL_FR_SPY_FRAMEFLAG_XXX values
     */
    public byte frameError;
    public byte tssLength;
    public short headerFlags;
    public short slotID;
    public short headerCRC;
    public byte payloadLength;
    public byte cycleCount;
    public byte frameFlags;
    public byte reserved;
    public int frameCRC;
    /**
     * C type : unsigned char[254]
     */
    public byte[] data = new byte[254];

    public s_xl_fr_spy_frame() {
        super(6);
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("frameLength", "frameError", "tssLength", "headerFlags", "slotID", "headerCRC", "payloadLength", "cycleCount", "frameFlags", "reserved", "frameCRC", "data");
    }

    public static class ByReference extends s_xl_fr_spy_frame implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_fr_spy_frame implements Structure.ByValue {

    }

    ;
}
