package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_fr_set_modes extends Structure {
    public int frMode;
    public int frStartupAttributes;
    /**
     * C type : unsigned int[30]
     */
    public int[] reserved = new int[30];

    public s_xl_fr_set_modes() {
        super(4);
    }

    /**
     * @param reserved C type : unsigned int[30]
     */
    public s_xl_fr_set_modes(int frMode, int frStartupAttributes, int reserved[]) {
        super(4);
        this.frMode = frMode;
        this.frStartupAttributes = frStartupAttributes;
        if ((reserved.length != this.reserved.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.reserved = reserved;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("frMode", "frStartupAttributes", "reserved");
    }

    public static class ByReference extends s_xl_fr_set_modes implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_fr_set_modes implements Structure.ByValue {

    }

    ;
}
