package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_most_async_msg extends Structure {
    /**
     * read as last data from PLD but stored first
     */
    public int status;
    /**
     * not used
     */
    public int crc;
    public byte arbitration;
    /**
     * real length of async data in quadlets
     */
    public byte length;
    public short targetAddress;
    public short sourceAddress;
    /**
     * max size but only used data is transmitted to pc<br>
     * C type : unsigned char[1018]
     */
    public byte[] asyncData = new byte[1018];

    public s_xl_most_async_msg() {
        super(8);
    }

    /**
     * @param status    read as last data from PLD but stored first<br>
     * @param crc       not used<br>
     * @param length    real length of async data in quadlets<br>
     * @param asyncData max size but only used data is transmitted to pc<br>
     *                  C type : unsigned char[1018]
     */
    public s_xl_most_async_msg(int status, int crc, byte arbitration, byte length, short targetAddress, short sourceAddress, byte asyncData[]) {
        super(8);
        this.status = status;
        this.crc = crc;
        this.arbitration = arbitration;
        this.length = length;
        this.targetAddress = targetAddress;
        this.sourceAddress = sourceAddress;
        if ((asyncData.length != this.asyncData.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.asyncData = asyncData;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("status", "crc", "arbitration", "length", "targetAddress", "sourceAddress", "asyncData");
    }

    public static class ByReference extends s_xl_most_async_msg implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_most_async_msg implements Structure.ByValue {

    }

    ;
}
