package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_sync_pulse_ev extends Structure {
    /**
     * !< e.g. external or internal trigger source
     */
    public int triggerSource;
    public int reserved;
    /**
     * !< internally generated timestamp<br>
     * C type : XLuint64
     */
    public long time;

    public s_xl_sync_pulse_ev() {
        super(8);
    }

    /**
     * @param triggerSource !< e.g. external or internal trigger source<br>
     * @param time          !< internally generated timestamp<br>
     *                      C type : XLuint64
     */
    public s_xl_sync_pulse_ev(int triggerSource, int reserved, long time) {
        super(8);
        this.triggerSource = triggerSource;
        this.reserved = reserved;
        this.time = time;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("triggerSource", "reserved", "time");
    }

    public static class ByReference extends s_xl_sync_pulse_ev implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_sync_pulse_ev implements Structure.ByValue {

    }

    ;
}
