package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_most150_async_tx_msg extends Structure {
    /**
     * Prio: Currently fixed to 0x00 for MDP /MEP
     */
    public int priority;
    /**
     * 1..16 attempts,set an invalid value to use the default value set by xlMost150SetAsyncRetryParameters
     */
    public int asyncSendAttempts;
    /**
     * max. 1600 bytes
     */
    public int length;
    public int targetAddress;
    /**
     * C type : unsigned char[(unsigned short)1600]
     */
    public byte[] asyncData = new byte[1600];

    public s_xl_most150_async_tx_msg() {
        super(1);
    }

    /**
     * @param priority          Prio: Currently fixed to 0x00 for MDP /MEP<br>
     * @param asyncSendAttempts 1..16 attempts,set an invalid value to use the default value set by xlMost150SetAsyncRetryParameters<br>
     * @param length            max. 1600 bytes<br>
     * @param asyncData         C type : unsigned char[(unsigned short)1600]
     */
    public s_xl_most150_async_tx_msg(int priority, int asyncSendAttempts, int length, int targetAddress, byte asyncData[]) {
        super(1);
        this.priority = priority;
        this.asyncSendAttempts = asyncSendAttempts;
        this.length = length;
        this.targetAddress = targetAddress;
        if ((asyncData.length != this.asyncData.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.asyncData = asyncData;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("priority", "asyncSendAttempts", "length", "targetAddress", "asyncData");
    }

    public static class ByReference extends s_xl_most150_async_tx_msg implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_most150_async_tx_msg implements Structure.ByValue {

    }

    ;
}
