package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;
import com.sun.jna.Union;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_eth_event extends Structure {
    /**
     * 4 - overall size of the complete event, depending on event type and piggybacked data
     */
    public int size;
    /**
     * 2 - type of the event<br>
     * C type : XLethEventTag
     */
    public short tag;
    /**
     * 2
     */
    public short channelIndex;
    /**
     * 4
     */
    public int userHandle;
    /**
     * 2
     */
    public short flagsChip;
    /**
     * 2
     */
    public short reserved;
    /**
     * 8<br>
     * C type : XLuint64
     */
    public long reserved1;
    /**
     * 8 - timestamp which is synchronized by the driver<br>
     * C type : XLuint64
     */
    public long timeStampSync;
    /**
     * C type : s_xl_eth_tag_data
     */
    public s_xl_eth_tag_data tagData;

    public s_xl_eth_event() {
        super(4);
    }

    ;

    /**
     * @param size          4 - overall size of the complete event, depending on event type and piggybacked data<br>
     * @param tag           2 - type of the event<br>
     *                      C type : XLethEventTag<br>
     * @param channelIndex  2<br>
     * @param userHandle    4<br>
     * @param flagsChip     2<br>
     * @param reserved      2<br>
     * @param reserved1     8<br>
     *                      C type : XLuint64<br>
     * @param timeStampSync 8 - timestamp which is synchronized by the driver<br>
     *                      C type : XLuint64<br>
     * @param tagData       C type : s_xl_eth_tag_data
     */
    public s_xl_eth_event(int size, short tag, short channelIndex, int userHandle, short flagsChip, short reserved, long reserved1, long timeStampSync, s_xl_eth_tag_data tagData) {
        super(4);
        this.size = size;
        this.tag = tag;
        this.channelIndex = channelIndex;
        this.userHandle = userHandle;
        this.flagsChip = flagsChip;
        this.reserved = reserved;
        this.reserved1 = reserved1;
        this.timeStampSync = timeStampSync;
        this.tagData = tagData;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("size", "tag", "channelIndex", "userHandle", "flagsChip", "reserved", "reserved1", "timeStampSync", "tagData");
    }

    /**
     * <i>native declaration : vxlapi.h:54</i>
     */
    public static class s_xl_eth_tag_data extends Union {
        /**
         * C type : unsigned char[(unsigned int)2048]
         */
        public byte[] rawData = new byte[2048];
        /**
         * (tag==XL_ETH_EVENT_TAG_FRAMERX)              Frame received from network<br>
         * C type : T_XL_ETH_DATAFRAME_RX
         */
        public s_xl_eth_dataframe_rx frameRxOk;
        /**
         * (tag==XL_ETH_EVENT_TAG_FRAMERX_ERROR)        Erroneous frame received from network<br>
         * C type : T_XL_ETH_DATAFRAME_RX_ERROR
         */
        public s_xl_eth_dataframe_rxerror frameRxError;
        /**
         * (tag==XL_ETH_EVENT_TAG_FRAMETX_ACK)          ACK for frame sent by application<br>
         * C type : T_XL_ETH_DATAFRAME_TXACK
         */
        public s_xl_eth_dataframe_tx_event frameTxAck;
        /**
         * (tag==XL_ETH_EVENT_TAG_FRAMETX_ACK_SWITCH)   ACK for frame sent by switch<br>
         * C type : T_XL_ETH_DATAFRAME_TXACK_SW
         */
        public s_xl_eth_dataframe_tx_event frameTxAckSw;
        /**
         * C type : T_XL_ETH_DATAFRAME_TXACK_OTHERAPP
         */
        public s_xl_eth_dataframe_tx_event frameTxAckOtherApp;
        /**
         * C type : T_XL_ETH_DATAFRAME_TX_ERROR
         */
        public s_xl_eth_dataframe_txerror frameTxError;
        /**
         * C type : T_XL_ETH_DATAFRAME_TX_ERR_SW
         */
        public s_xl_eth_dataframe_txerror frameTxErrorSw;
        /**
         * (e.g. queue full condition)<br>
         * C type : T_XL_ETH_DATAFRAME_TX_ERR_OTHERAPP
         */
        public s_xl_eth_dataframe_txerror frameTxErrorOtherApp;
        /**
         * C type : T_XL_ETH_CONFIG_RESULT
         */
        public s_xl_eth_config_result configResult;
        /**
         * C type : T_XL_ETH_CHANNEL_STATUS
         */
        public s_xl_eth_channel_status channelStatus;
        /**
         * C type : XL_SYNC_PULSE_EV
         */
        public s_xl_sync_pulse_ev syncPulse;
        /**
         * (tag==XL_ETH_EVENT_TAG_LOSTEVENT)          Indication that one or more events have been lost<br>
         * C type : T_XL_ETH_LOSTEVENT
         */
        public s_xl_eth_lostevent lostEvent;

        public s_xl_eth_tag_data() {
            super();
        }

        /**
         * @param rawData C type : unsigned char[(unsigned int)2048]
         */
        public s_xl_eth_tag_data(byte rawData[]) {
            super();
            if ((rawData.length != this.rawData.length))
                throw new IllegalArgumentException("Wrong array size !");
            this.rawData = rawData;
            setType(byte[].class);
        }

        /**
         * @param channelStatus C type : T_XL_ETH_CHANNEL_STATUS
         */
        public s_xl_eth_tag_data(s_xl_eth_channel_status channelStatus) {
            super();
            this.channelStatus = channelStatus;
            setType(s_xl_eth_channel_status.class);
        }

        /**
         * @param syncPulse C type : XL_SYNC_PULSE_EV
         */
        public s_xl_eth_tag_data(s_xl_sync_pulse_ev syncPulse) {
            super();
            this.syncPulse = syncPulse;
            setType(s_xl_sync_pulse_ev.class);
        }

        /**
         * @param configResult C type : T_XL_ETH_CONFIG_RESULT
         */
        public s_xl_eth_tag_data(s_xl_eth_config_result configResult) {
            super();
            this.configResult = configResult;
            setType(s_xl_eth_config_result.class);
        }

        /**
         * @param frameRxOk (tag==XL_ETH_EVENT_TAG_FRAMERX)              Frame received from network<br>
         *                  C type : T_XL_ETH_DATAFRAME_RX
         */
        public s_xl_eth_tag_data(s_xl_eth_dataframe_rx frameRxOk) {
            super();
            this.frameRxOk = frameRxOk;
            setType(s_xl_eth_dataframe_rx.class);
        }

        /**
         * @param frameTxError_or_frameTxErrorSw_or_frameTxErrorOtherApp C type : T_XL_ETH_DATAFRAME_TX_ERROR, or C type : T_XL_ETH_DATAFRAME_TX_ERR_SW, or (e.g. queue full condition)<br>
         *                                                               C type : T_XL_ETH_DATAFRAME_TX_ERR_OTHERAPP
         */
        public s_xl_eth_tag_data(s_xl_eth_dataframe_txerror frameTxError_or_frameTxErrorSw_or_frameTxErrorOtherApp) {
            super();
            this.frameTxErrorOtherApp = this.frameTxErrorSw = this.frameTxError = frameTxError_or_frameTxErrorSw_or_frameTxErrorOtherApp;
            setType(s_xl_eth_dataframe_txerror.class);
        }

        /**
         * @param frameRxError (tag==XL_ETH_EVENT_TAG_FRAMERX_ERROR)        Erroneous frame received from network<br>
         *                     C type : T_XL_ETH_DATAFRAME_RX_ERROR
         */
        public s_xl_eth_tag_data(s_xl_eth_dataframe_rxerror frameRxError) {
            super();
            this.frameRxError = frameRxError;
            setType(s_xl_eth_dataframe_rxerror.class);
        }

        /**
         * @param frameTxAck_or_frameTxAckSw_or_frameTxAckOtherApp (tag==XL_ETH_EVENT_TAG_FRAMETX_ACK)          ACK for frame sent by application<br>
         *                                                         C type : T_XL_ETH_DATAFRAME_TXACK, or (tag==XL_ETH_EVENT_TAG_FRAMETX_ACK_SWITCH)   ACK for frame sent by switch<br>
         *                                                         C type : T_XL_ETH_DATAFRAME_TXACK_SW, or C type : T_XL_ETH_DATAFRAME_TXACK_OTHERAPP
         */
        public s_xl_eth_tag_data(s_xl_eth_dataframe_tx_event frameTxAck_or_frameTxAckSw_or_frameTxAckOtherApp) {
            super();
            this.frameTxAckOtherApp = this.frameTxAckSw = this.frameTxAck = frameTxAck_or_frameTxAckSw_or_frameTxAckOtherApp;
            setType(s_xl_eth_dataframe_tx_event.class);
        }

        /**
         * @param lostEvent (tag==XL_ETH_EVENT_TAG_LOSTEVENT)          Indication that one or more events have been lost<br>
         *                  C type : T_XL_ETH_LOSTEVENT
         */
        public s_xl_eth_tag_data(s_xl_eth_lostevent lostEvent) {
            super();
            this.lostEvent = lostEvent;
            setType(s_xl_eth_lostevent.class);
        }

        public static class ByReference extends s_xl_eth_tag_data implements Structure.ByReference {

        }

        ;

        public static class ByValue extends s_xl_eth_tag_data implements Structure.ByValue {

        }

        ;
    }

    public static class ByReference extends s_xl_eth_event implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_eth_event implements Structure.ByValue {

    }

    ;
}
