package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_kline_set_com_ecu extends Structure {
    /**
     * !< [us]
     */
    public int P1;
    /**
     * !< [us]
     */
    public int P4min;
    /**
     * !< [us]
     */
    public int TinilMin;
    /**
     * !< [us]
     */
    public int TinilMax;
    /**
     * !< [us]
     */
    public int TwupMin;
    /**
     * !< [us]
     */
    public int TwupMax;
    public int reserved;

    public s_xl_kline_set_com_ecu() {
        super(8);
    }

    /**
     * @param P1       !< [us]<br>
     * @param P4min    !< [us]<br>
     * @param TinilMin !< [us]<br>
     * @param TinilMax !< [us]<br>
     * @param TwupMin  !< [us]<br>
     * @param TwupMax  !< [us]
     */
    public s_xl_kline_set_com_ecu(int P1, int P4min, int TinilMin, int TinilMax, int TwupMin, int TwupMax, int reserved) {
        super(8);
        this.P1 = P1;
        this.P4min = P4min;
        this.TinilMin = TinilMin;
        this.TinilMax = TinilMax;
        this.TwupMin = TwupMin;
        this.TwupMax = TwupMax;
        this.reserved = reserved;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("P1", "P4min", "TinilMin", "TinilMax", "TwupMin", "TwupMax", "reserved");
    }

    public static class ByReference extends s_xl_kline_set_com_ecu implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_kline_set_com_ecu implements Structure.ByValue {

    }

    ;
}
