package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_io_analog_data extends Structure {
    public int measuredAnalogData0;
    public int measuredAnalogData1;
    public int measuredAnalogData2;
    public int measuredAnalogData3;

    public s_xl_io_analog_data() {
        super(1);
    }

    public s_xl_io_analog_data(int measuredAnalogData0, int measuredAnalogData1, int measuredAnalogData2, int measuredAnalogData3) {
        super(1);
        this.measuredAnalogData0 = measuredAnalogData0;
        this.measuredAnalogData1 = measuredAnalogData1;
        this.measuredAnalogData2 = measuredAnalogData2;
        this.measuredAnalogData3 = measuredAnalogData3;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("measuredAnalogData0", "measuredAnalogData1", "measuredAnalogData2", "measuredAnalogData3");
    }

    public static class ByReference extends s_xl_io_analog_data implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_io_analog_data implements Structure.ByValue {

    }

    ;
}
