package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_eth_frame extends Structure {
    /**
     * Ethernet type in network byte order
     */
    public short etherType;
    /**
     * C type : unsigned char[(unsigned int)1500]
     */
    public byte[] payload = new byte[1500];

    public s_xl_eth_frame() {
        super(1);
    }

    /**
     * @param etherType Ethernet type in network byte order<br>
     * @param payload   C type : unsigned char[(unsigned int)1500]
     */
    public s_xl_eth_frame(short etherType, byte payload[]) {
        super(1);
        this.etherType = etherType;
        if ((payload.length != this.payload.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.payload = payload;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("etherType", "payload");
    }

    public static class ByReference extends s_xl_eth_frame implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_eth_frame implements Structure.ByValue {

    }

    ;
}
