package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_remote_device extends Structure {
    /**
     * C type : char[32]
     */
    public byte[] deviceName = new byte[32];
    public int hwType;
    public int articleNumber;
    public int serialNumber;
    public int reserved;

    public s_xl_remote_device() {
        super(8);
    }

    /**
     * @param deviceName C type : char[32]
     */
    public s_xl_remote_device(byte deviceName[], int hwType, int articleNumber, int serialNumber, int reserved) {
        super(8);
        if ((deviceName.length != this.deviceName.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.deviceName = deviceName;
        this.hwType = hwType;
        this.articleNumber = articleNumber;
        this.serialNumber = serialNumber;
        this.reserved = reserved;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("deviceName", "hwType", "articleNumber", "serialNumber", "reserved");
    }

    public static class ByReference extends s_xl_remote_device implements Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_remote_device implements Structure.ByValue {

    }

    ;
}
