package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Union;

/**
 * LIN messages structure<br>
 * <i>native declaration : vxlapi.h:243</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class s_xl_lin_msg_api extends Union {
    /**
     * C type : s_xl_lin_msg
     */
    public s_xl_lin_msg linMsg;
    /**
     * C type : s_xl_lin_no_ans
     */
    public s_xl_lin_no_ans linNoAns;
    /**
     * C type : s_xl_lin_wake_up
     */
    public s_xl_lin_wake_up linWakeUp;
    /**
     * C type : s_xl_lin_sleep
     */
    public s_xl_lin_sleep linSleep;
    /**
     * C type : s_xl_lin_crc_info
     */
    public s_xl_lin_crc_info linCRCinfo;

    public s_xl_lin_msg_api() {
        super();
    }

    /**
     * @param linWakeUp C type : s_xl_lin_wake_up
     */
    public s_xl_lin_msg_api(s_xl_lin_wake_up linWakeUp) {
        super();
        this.linWakeUp = linWakeUp;
        setType(s_xl_lin_wake_up.class);
    }

    /**
     * @param linMsg C type : s_xl_lin_msg
     */
    public s_xl_lin_msg_api(s_xl_lin_msg linMsg) {
        super();
        this.linMsg = linMsg;
        setType(s_xl_lin_msg.class);
    }

    /**
     * @param linSleep C type : s_xl_lin_sleep
     */
    public s_xl_lin_msg_api(s_xl_lin_sleep linSleep) {
        super();
        this.linSleep = linSleep;
        setType(s_xl_lin_sleep.class);
    }

    /**
     * @param linCRCinfo C type : s_xl_lin_crc_info
     */
    public s_xl_lin_msg_api(s_xl_lin_crc_info linCRCinfo) {
        super();
        this.linCRCinfo = linCRCinfo;
        setType(s_xl_lin_crc_info.class);
    }

    /**
     * @param linNoAns C type : s_xl_lin_no_ans
     */
    public s_xl_lin_msg_api(s_xl_lin_no_ans linNoAns) {
        super();
        this.linNoAns = linNoAns;
        setType(s_xl_lin_no_ans.class);
    }

    public static class ByReference extends s_xl_lin_msg_api implements com.sun.jna.Structure.ByReference {

    }

    ;

    public static class ByValue extends s_xl_lin_msg_api implements com.sun.jna.Structure.ByValue {

    }

    ;
}
