package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class T_XL_ETH_CONFIG extends Structure {
    /**
     * (XL_ETH_MODE_SPEED_*)       Connection speed setting
     */
    public int speed;
    public int duplex;
    /**
     * (XL_ETH_MODE_CONNECTOR_*)   Connector to use
     */
    public int connector;
    /**
     * (XL_ETH_MODE_PHY_*)         Physical interface to enable
     */
    public int phy;
    /**
     * (XL_ETH_MODE_CLOCK_*)       Master or slave clock mode setting (1000Base-T/BroadR-REACH mode only).
     */
    public int clockMode;
    /**
     * (XL_ETH_MODE_MDI_*)         Currently active MDI-mode
     */
    public int mdiMode;
    /**
     * (XL_ETH_MODE_BR_PAIR_*)     Number of cable pairs to use (BroadR-REACH mode only).
     */
    public int brPairs;

    public T_XL_ETH_CONFIG() {
        super(4);
    }

    /**
     * @param speed     (XL_ETH_MODE_SPEED_*)       Connection speed setting<br>
     * @param connector (XL_ETH_MODE_CONNECTOR_*)   Connector to use<br>
     * @param phy       (XL_ETH_MODE_PHY_*)         Physical interface to enable<br>
     * @param clockMode (XL_ETH_MODE_CLOCK_*)       Master or slave clock mode setting (1000Base-T/BroadR-REACH mode only).<br>
     * @param mdiMode   (XL_ETH_MODE_MDI_*)         Currently active MDI-mode<br>
     * @param brPairs   (XL_ETH_MODE_BR_PAIR_*)     Number of cable pairs to use (BroadR-REACH mode only).
     */
    public T_XL_ETH_CONFIG(int speed, int duplex, int connector, int phy, int clockMode, int mdiMode, int brPairs) {
        super(4);
        this.speed = speed;
        this.duplex = duplex;
        this.connector = connector;
        this.phy = phy;
        this.clockMode = clockMode;
        this.mdiMode = mdiMode;
        this.brPairs = brPairs;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("speed", "duplex", "connector", "phy", "clockMode", "mdiMode", "brPairs");
    }

    public static class ByReference extends T_XL_ETH_CONFIG implements Structure.ByReference {

    }

    ;

    public static class ByValue extends T_XL_ETH_CONFIG implements Structure.ByValue {

    }

    ;
}
