package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Collections;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class T_XL_ETH_MAC_ADDRESS extends Structure {
    /**
     * C type : unsigned char[6]
     */
    public byte[] address = new byte[6];

    public T_XL_ETH_MAC_ADDRESS() {
        super(4);
    }

    /**
     * @param address C type : unsigned char[6]
     */
    public T_XL_ETH_MAC_ADDRESS(byte[] address) {
        super(4);
        if ((address.length != this.address.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.address = address;
    }

    protected List<String> getFieldOrder() {
        return Collections.singletonList("address");
    }

    public static class ByReference extends T_XL_ETH_MAC_ADDRESS implements Structure.ByReference {

    }

    ;

    public static class ByValue extends T_XL_ETH_MAC_ADDRESS implements Structure.ByValue {

    }

    ;
}
