package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class XL_CAN_TX_MSG extends Structure {
    public int canId;
    public int msgFlags;
    public byte dlc;
    /**
     * C type : unsigned char[7]
     */
    public byte[] reserved = new byte[7];
    /**
     * C type : unsigned char[64]
     */
    public byte[] data = new byte[64];

    public XL_CAN_TX_MSG() {
        super(8);
    }

    /**
     * @param reserved C type : unsigned char[7]<br>
     * @param data     C type : unsigned char[64]
     */
    public XL_CAN_TX_MSG(int canId, int msgFlags, byte dlc, byte[] reserved, byte[] data) {
        super(8);
        this.canId = canId;
        this.msgFlags = msgFlags;
        this.dlc = dlc;
        if ((reserved.length != this.reserved.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.reserved = reserved;
        if ((data.length != this.data.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.data = data;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("canId", "msgFlags", "dlc", "reserved", "data");
    }

    public static class ByReference extends XL_CAN_TX_MSG implements Structure.ByReference {

    }

    ;

    public static class ByValue extends XL_CAN_TX_MSG implements Structure.ByValue {

    }

    ;
}
