package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xl_daio_digital_params extends Structure {
    /**
     * !< Use defines XL_DAIO_PORT_MASK_DIGITAL_*
     */
    public int portMask;
    /**
     * !< Specify the port value (ON/HIGH - 1 | OFF/LOW - 0)
     */
    public int valueMask;

    public xl_daio_digital_params() {
        super(8);
    }

    /**
     * @param portMask  !< Use defines XL_DAIO_PORT_MASK_DIGITAL_*<br>
     * @param valueMask !< Specify the port value (ON/HIGH - 1 | OFF/LOW - 0)
     */
    public xl_daio_digital_params(int portMask, int valueMask) {
        super(8);
        this.portMask = portMask;
        this.valueMask = valueMask;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("portMask", "valueMask");
    }

    public static class ByReference extends xl_daio_digital_params implements Structure.ByReference {

    }

    ;

    public static class ByValue extends xl_daio_digital_params implements Structure.ByValue {

    }

    ;
}
