package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;
import com.sun.jna.Union;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class XLa429RxEvent extends Structure {
    /**
     * 4 - overall size of the complete event
     */
    public int size;
    /**
     * 2 - type of the event
     */
    public short tag;
    /**
     * 1
     */
    public byte channelIndex;
    /**
     * 1
     */
    public byte reserved;
    /**
     * 4 (lower 12 bit available for CAN)
     */
    public int userHandle;
    /**
     * 2 queue overflow (upper 8bit)
     */
    public short flagsChip;
    /**
     * 1
     */
    public short reserved0;
    /**
     * 8 - raw timestamp<br>
     * C type : XLuint64
     */
    public long timeStamp;
    /**
     * 8 - timestamp which is synchronized by the driver<br>
     * C type : XLuint64
     */
    public long timeStampSync;
    /**
     * C type : tagData_union
     */
    public tagData_union tagData;

    public XLa429RxEvent() {
        super(8);
    }

    ;

    protected List<String> getFieldOrder() {
        return Arrays.asList("size", "tag", "channelIndex", "reserved", "userHandle", "flagsChip", "reserved0", "timeStamp", "timeStampSync", "tagData");
    }

    /**
     * <i>native declaration : vxlapi.h:192</i>
     */
    public static class tagData_union extends Union {
        /**
         * C type : XL_A429_EV_TX_OK
         */
        public s_xl_a429_ev_tx_ok a429TxOkMsg;
        /**
         * C type : XL_A429_EV_TX_ERR
         */
        public s_xl_a429_ev_tx_err a429TxErrMsg;
        /**
         * C type : XL_A429_EV_RX_OK
         */
        public s_xl_a429_ev_rx_ok a429RxOkMsg;
        /**
         * C type : XL_A429_EV_RX_ERR
         */
        public s_xl_a429_ev_rx_err a429RxErrMsg;
        /**
         * C type : XL_A429_EV_BUS_STATISTIC
         */
        public s_xl_a429_ev_bus_statistic a429BusStatistic;
        /**
         * C type : XL_A429_EV_SYNC_PULSE
         */
        public s_xl_sync_pulse_ev a429SyncPulse;

        public tagData_union() {
            super();
        }

        /**
         * @param a429BusStatistic C type : XL_A429_EV_BUS_STATISTIC
         */
        public tagData_union(s_xl_a429_ev_bus_statistic a429BusStatistic) {
            super();
            this.a429BusStatistic = a429BusStatistic;
            setType(s_xl_a429_ev_bus_statistic.class);
        }

        /**
         * @param a429SyncPulse C type : XL_A429_EV_SYNC_PULSE
         */
        public tagData_union(s_xl_sync_pulse_ev a429SyncPulse) {
            super();
            this.a429SyncPulse = a429SyncPulse;
            setType(s_xl_sync_pulse_ev.class);
        }

        /**
         * @param a429TxErrMsg C type : XL_A429_EV_TX_ERR
         */
        public tagData_union(s_xl_a429_ev_tx_err a429TxErrMsg) {
            super();
            this.a429TxErrMsg = a429TxErrMsg;
            setType(s_xl_a429_ev_tx_err.class);
        }

        /**
         * @param a429RxOkMsg C type : XL_A429_EV_RX_OK
         */
        public tagData_union(s_xl_a429_ev_rx_ok a429RxOkMsg) {
            super();
            this.a429RxOkMsg = a429RxOkMsg;
            setType(s_xl_a429_ev_rx_ok.class);
        }

        /**
         * @param a429RxErrMsg C type : XL_A429_EV_RX_ERR
         */
        public tagData_union(s_xl_a429_ev_rx_err a429RxErrMsg) {
            super();
            this.a429RxErrMsg = a429RxErrMsg;
            setType(s_xl_a429_ev_rx_err.class);
        }

        /**
         * @param a429TxOkMsg C type : XL_A429_EV_TX_OK
         */
        public tagData_union(s_xl_a429_ev_tx_ok a429TxOkMsg) {
            super();
            this.a429TxOkMsg = a429TxOkMsg;
            setType(s_xl_a429_ev_tx_ok.class);
        }

        public static class ByReference extends tagData_union implements Structure.ByReference {

        }

        ;

        public static class ByValue extends tagData_union implements Structure.ByValue {

        }

        ;
    }

    public static class ByReference extends XLa429RxEvent implements Structure.ByReference {

    }

    ;

    public static class ByValue extends XLa429RxEvent implements Structure.ByValue {

    }

    ;
}
