package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * structure for the acceptance filter of one CAN chip<br>
 * <i>native declaration : vxlapi.h:706</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class XLacceptance extends Structure {
    /**
     * C type : XLaccFilt
     */
    public _XLacc_filt std;
    /**
     * C type : XLaccFilt
     */
    public _XLacc_filt xtd;

    public XLacceptance() {
        super(1);
    }

    /**
     * @param std C type : XLaccFilt<br>
     * @param xtd C type : XLaccFilt
     */
    public XLacceptance(_XLacc_filt std, _XLacc_filt xtd) {
        super(1);
        this.std = std;
        this.xtd = xtd;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("std", "xtd");
    }

    public static class ByReference extends XLacceptance implements Structure.ByReference {

    }

    ;

    public static class ByValue extends XLacceptance implements Structure.ByValue {

    }

    ;
}
