package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class XLcanFdConf extends Structure {
    public int arbitrationBitRate;
    /**
     * CAN bus timing for nominal / arbitration bit rate
     */
    public int sjwAbr;
    public int tseg1Abr;
    public int tseg2Abr;
    public int dataBitRate;
    /**
     * CAN bus timing for data bit rate
     */
    public int sjwDbr;
    public int tseg1Dbr;
    public int tseg2Dbr;
    /**
     * has to be zero
     */
    public byte reserved;
    /**
     * CANFD_CONFOPT_
     */
    public byte options;
    /**
     * has to be zero<br>
     * C type : unsigned char[2]
     */
    public byte[] reserved1 = new byte[2];
    /**
     * has to be zero
     */
    public int reserved2;

    public XLcanFdConf() {
        super(1);
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("arbitrationBitRate", "sjwAbr", "tseg1Abr", "tseg2Abr", "dataBitRate", "sjwDbr", "tseg1Dbr", "tseg2Dbr", "reserved", "options", "reserved1", "reserved2");
    }

    public static class ByReference extends XLcanFdConf implements Structure.ByReference {

    }

    ;

    public static class ByValue extends XLcanFdConf implements Structure.ByValue {

    }

    ;
}
