package pers.fsh.deviceutils.hardware.vectorhardware.mapping;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : vxlapi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class XLchipParams extends Structure {
    public int bitRate;
    public byte sjw;
    public byte tseg1;
    public byte tseg2;
    /**
     * 1 or 3
     */
    public byte sam;

    public XLchipParams() {
        super(1);
    }

    /**
     * @param sam 1 or 3
     */
    public XLchipParams(int bitRate, byte sjw, byte tseg1, byte tseg2, byte sam) {
        super(1);
        this.bitRate = bitRate;
        this.sjw = sjw;
        this.tseg1 = tseg1;
        this.tseg2 = tseg2;
        this.sam = sam;
    }

    protected List<String> getFieldOrder() {
        return Arrays.asList("bitRate", "sjw", "tseg1", "tseg2", "sam");
    }

    public static class ByReference extends XLchipParams implements Structure.ByReference {

    }

    ;

    public static class ByValue extends XLchipParams implements Structure.ByValue {

    }

    ;
}
